create (a:N {labels: "a"}),
       (b:N {labels: "b"}),
       (c:N {labels: "c"}),
       (d:N {labels: "d"}),
       (w:N {labels: "w"}),
       (x:N {labels: "x"}),
       (y:N {labels: "y"}),
       (z:N {labels: "z"}),
       (a)-[:relateTo]->(b),
       (b)-[:relateTo]->(d),
       (d)-[:relateTo]->(c),
       (c)-[:relateTo]->(a),
       (a)-[:relateTo]->(d),
       (c)-[:relateTo]->(b),
       (w)-[:relateTo]->(a),
       (x)-[:relateTo]->(b),
       (y)-[:relateTo]->(d),
       (z)-[:relateTo]->(c)
