version: '2'
services:
  neo4j:
    image: neo4j:3.1.1
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./data:/data
      - ./import:/var/lib/neo4j/import
      - ./plugins:/var/lib/neo4j/plugins
